### PR TITLE
Add 64-bit IDA 7.2 support (thx @Maroc-OS)

### PR DESCRIPTION
**Pull request by vit9696**
This rebases https://github.com/avast-tl/retdec-idaplugin/pull/31 against master and fixes IDA 7.2 support. Feel free to take over if you need it.

### CODE REVIEW

**Comment by PeterMatula** [comment]
@vit9696 and @Maroc-OS please help.

I merged this to branch `pull-36` to play with it and I have a few questions:
* Is that `RetDecUInt` really necessary? Did you encounter problems with `%a`. I tried `%a` on my Linux IDA in both 32-bit and 64-bit address spaces and it seems ok. In what scenario was it misbehaving, and what was the result?
* Do you happen to know what that `%a` even wants to represent? Printf's doc says _Hexadecimal floating point, lowercase_, but I'm not 100% sure that is it. Example plugins in IDA SDK commonly use it to print addresses, and if its meaning is an address, then maybe IDA SDK takes care of it and there is no need to hack it by using `RetDecUInt`.
* Was that construction `if (EA64 GREATER_EQUAL 1)` working for you? I guess it works if `-DEA64=1`, but it did not work for me when I did `-DEA64=ON`. Is there some reason to prefer it over `if (EA64)`?
* On several places there are changes in parameters in functions such as `ask_str()` and `ask_file()`. Did something change in the SDK, or was it wrong even before? What SDK should be used to build this code? If this is to support some new SDK (e.g. 7.2) can the plugin be build with 7.0 with these changes?
* Why use this
```cpp
#ifdef OS_WINDOWS
	pluginConfigFile.append("\\" + pluginConfigFileName);
#else // Linux & macOS
	pluginConfigFile.append("/" + pluginConfigFileName);
#endif
```
instead of the original
```
pluginConfigFile.append(pluginConfigFileName);
```
wasn't it working? `FilesystemPath` should take care of this. If it does not, we should fix it.

**Comment by vit9696** [comment]
@PeterMatula I was not the author for most of the changes, but I believe I am qualified to answer some of your questions. 

- You are right that standard compliant `%a` is a hexadecimal floating point, and thus it had to be changed. I have the standards nearby, and can confirm that the the description is pretty close for C99, C11, and C18. However, it is not present in ANSI C (C89). Most likely some old (and even current) compilers not supporting C99 abused that specifier. Here is the quote from ISO 9899 2018:
  ```
  a, A

  A double argument representing a foating-point number is converted in the style
  [-]0xh.hhhhp±d, where there is one hexadecimal digit (which is nonzero if the argument is a
  normalized foating-point number and is otherwise unspecifed) before the decimal-point
  character284) and the number of hexadecimal digits after it is equal to the precision; if the
  precision is missing and FLT_RADIX is a power of 2, then the precision is suffcient for an
  exact representation of the value; if the precision is missing and FLT_RADIX is not a power
  of 2, then the precision is suffcient to distinguish285) values of type double, except that
  trailing zeros may be omitted; if the precision is zero and the # fag is not specifed, no
  decimal-point character appears. The letters abcdef are used for a conversion and the
  letters ABCDEF for A conversion. The A conversion specifer produces a number with X and
  P instead of x and p. The exponent always contains at least one digit, and only as many
  more digits as necessary to represent the decimal exponent of 2. If the value is zero, the
  exponent is zero.

  A double argument representing an infnity or NaN is converted in the style of an f or F
  conversion specifer.
  ```

  If you check IDA SDK docs you will find that you need to use idamake.pl to fix `%a` printing for GCC and Clang:
  ```
    You may also run the 'idamake.pl' script instead of 'make'. It is a post-
    processing script for make, and will prevent the printing of some warnings
    which cannot be disabled in the compiler. For example, there is this warning
    from gcc:

      warning: format ‘%a’ expects argument of type ‘double’, but argument 2 has type ‘ea_t {aka unsigned int}’ [-Wformat=]
  ```

  So yes, it is pretty much necessary.

- I managed to build both 32-bit and 64-bit variants of a plugin, and the code works fine with `EA64=1` (not to be confused with `-DEA64=1`). I am familiar with the cmake, and cannot easily tell   whether `OFF` and `ON` are parsed anyhow different in `if (EA64)`. Suspect they may not be. In my opinion, it should either stay as is, or get an extra check for `ON`. In either case, cmake docs are to be properly studied.

- Regarding the string functions, from what I remember there were numerous warnings (and in fact fatal errors) about passing non-literals to the printf-like functions. I used the 7.2 SDK, but I do not think that the previous SDKs (like 7.0) were any different. Most likely older compilers/SDKs were just more forgiving. I believe it should still be buildable with 7.0.

- As for `pluginConfigFile.append`, it was in the original patch, and actually I am not positive that it definitely fails. Do you think there is any room for an issue like not adding any slash at all? In my opinion, that was the point of appending the suffix manually.

Kind regards,
Vit

**Comment by PeterMatula** [comment]
Thanks, very informative.

**Comment by PeterMatula** [comment]
C++ stream-style messages in a34521c31ea3e65256344efb3e964bc03d426383 should solve these printf-style `%*` issues once and for all.

**Comment by vit9696** [comment]
Hmm, I do not have a compiler nearby, but this does not look totally right. Since `msg` takes a formatted string, you basically made it even more dangerous by passing a stringstream casted to a C string. Make it `msg("%s", ...c_str());` in my opinion.

**Comment by PeterMatula** [comment]
Hmm, now you made me think, but I don't think there is a problem. Stringstream solves all the format specifiers and produces `const char*` which is exactly what `msg(const char *format, ...)` accepts. I don't see why `format` could not be the whole string we want to print, and `...` empty.
I might be wrong, so if you think of some concrete problem with it, let me know.

**Comment by PeterMatula** [comment]
> ... more dangerous by passing a stringstream casted to a C string ...

I don't think _casted_ is the right word here, `std::stringstream::str()` produces `std::string`, `std::string::c_str()` produces proper `const char*` - _a pointer to an array that contains a null-terminated sequence of characters_. It is not casting the `std::string` object.

**Comment by vit9696** [comment]
I am talking about an accidental presence of `%` in the resulting string due to unrelated causes. Since it is a C++ formatted string for the user of the API, it may sometimes be unobvious that some input sequences are potentially disallowed.

Due to [uncontrolled format string](
https://en.m.wikipedia.org/wiki/Uncontrolled_format_string) vulnerabilities modern compilers started to warn about passing non literal arguments to printf-like functions, so this is enough for me for a reason to rewrite the code to look like `msg("%s", arg)`.

**Comment by PeterMatula** [comment]
That makes sense. Changed in 6937994dfba2734b255f25dcb7328b0a3cf726f1.

**Comment by PeterMatula** [comment]
@Maroc-OS I reverted the manual adding of separators to file system paths using `#ifdef OS_WINDOWS` in 60ee8342ed3ff05cd17b5c9a3c484d50cb02e39a. This should be handled by `retdec::utils::FilesystemPath` without these ugly ifdefs. If there is some problem and it is not working for you (maybe something macOS related?) please create a new issue and describe the problem.

**Comment by vit9696** [comment]
@PeterMatula thanks for the changes.

I compiled your branch and it appears to work fine for me. I also built it with 7.0 SP1 SDK, and can confirm that it at least compiles.
 
- I did not notice any issue without the path ifdefs so far. Perhaps it was an old bug, that is now fixed.
- `if (NOT EA64)` appears to be slightly problematic, as the value is cached upon first invocation. I do not remember this behaviour with the previous code.
  After you run `cmake .. -DEA64=1` for the first time, running `cmake ..` a second time will still build for 64-bit address space. You have to write `cmake .. -DEA64=0` explicitly to get a 32-bit address space build.
  For this very reason I reworded the hint, to make it least confusing for the user.
- It looks like you did not change the call style to another printf-like function: `message`. Fixed it as well.


```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 802efce..e9a53e9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -23,9 +23,9 @@ if(NOT EXISTS "${IDA_SDK_DIR}")
 	message(FATAL_ERROR "Specified IDA SDK path does not exist.")
 endif()
 if(NOT EA64)
-	message("We are building RetDec for ida pro 7 32bits address space, Use -DEA64=1. to Enable building for 64bits address space.")
+	message("We are building RetDec for IDA Pro 7 32-bit address space. Use -DEA64=1 to enable building for 64-bit address space.")
 else()
-	message("Configuring RetDec build for ida pro 7 64bits address space.")
+	message("Configuring RetDec build for IDA Pro 7 64-bit address space. Use -DEA64=0 to enable building for 32-bit address space.")
 	add_definitions ( -DEA64="ON" )
 endif()
 
diff --git a/src/idaplugin/defs.h b/src/idaplugin/defs.h
index d5db013..1bd1b51 100644
--- a/src/idaplugin/defs.h
+++ b/src/idaplugin/defs.h
@@ -65,7 +65,7 @@ namespace idaplugin {
 #define INFO_MSG(body)    if (PRINT_INFO)    { std::stringstream ss; ss << std::showbase << "[RetDec info]   :\t" << body; msg("%s", ss.str().c_str()); }
 
 /// Use instead of IDA SDK's warning() function.
-#define WARNING_GUI(body) { std::stringstream ss; ss << std::showbase << body; warning(ss.str().c_str()); }
+#define WARNING_GUI(body) { std::stringstream ss; ss << std::showbase << body; warning("%s", ss.str().c_str()); }
 
 class FunctionInfo
 {
```

**Comment by PeterMatula** [comment]
@vit9696
* Thanks for the `WARNING_GUI()` change, I forgot about it. 
* Now I'm satisfied with the C++ sources in the branch, but not yet with the CMake sources. I don't like the negative condition `if (NOT EA64)`, wording of the messages, `if(EA64 GREATER_EQUAL 1)` condition, and maybe some other things, so I will definitely make some more changes before merging it to `master`.

Btw, that behavior regarding `cmake .. -DEA64={0,1}` is expected. Other definitions in this repo or `retdec` repo behave the same. Once CMake is configured, it will repeat the build as configured, until it is not re-configured.

**Comment by Maroc-OS** [comment]
> @PeterMatula I was not the author for most of the changes, but I believe I am qualified to answer some of your questions.
> 
>     * You are right that standard compliant `%a` is a hexadecimal floating point, and thus it had to be changed. I have the standards nearby, and can confirm that the the description is pretty close for C99, C11, and C18. However, it is not present in ANSI C (C89). Most likely some old (and even current) compilers not supporting C99 abused that specifier. Here is the quote from ISO 9899 2018:
>       ```
>       a, A
>       
>       A double argument representing a foating-point number is converted in the style
>       [-]0xh.hhhhp±d, where there is one hexadecimal digit (which is nonzero if the argument is a
>       normalized foating-point number and is otherwise unspecifed) before the decimal-point
>       character284) and the number of hexadecimal digits after it is equal to the precision; if the
>       precision is missing and FLT_RADIX is a power of 2, then the precision is suffcient for an
>       exact representation of the value; if the precision is missing and FLT_RADIX is not a power
>       of 2, then the precision is suffcient to distinguish285) values of type double, except that
>       trailing zeros may be omitted; if the precision is zero and the # fag is not specifed, no
>       decimal-point character appears. The letters abcdef are used for a conversion and the
>       letters ABCDEF for A conversion. The A conversion specifer produces a number with X and
>       P instead of x and p. The exponent always contains at least one digit, and only as many
>       more digits as necessary to represent the decimal exponent of 2. If the value is zero, the
>       exponent is zero.
>       
>       A double argument representing an infnity or NaN is converted in the style of an f or F
>       conversion specifer.
>       ```
>       If you check IDA SDK docs you will find that you need to use idamake.pl to fix `%a` printing for GCC and Clang:
>       ```
>         You may also run the 'idamake.pl' script instead of 'make'. It is a post-
>         processing script for make, and will prevent the printing of some warnings
>         which cannot be disabled in the compiler. For example, there is this warning
>         from gcc:
>       
>           warning: format ‘%a’ expects argument of type ‘double’, but argument 2 has type ‘ea_t {aka unsigned int}’ [-Wformat=]
>       ```
>       So yes, it is pretty much necessary.
> 
>     * I managed to build both 32-bit and 64-bit variants of a plugin, and the code works fine with `EA64=1` (not to be confused with `-DEA64=1`). I am familiar with the cmake, and cannot easily tell   whether `OFF` and `ON` are parsed anyhow different in `if (EA64)`. Suspect they may not be. In my opinion, it should either stay as is, or get an extra check for `ON`. In either case, cmake docs are to be properly studied.
> 
>     * Regarding the string functions, from what I remember there were numerous warnings (and in fact fatal errors) about passing non-literals to the printf-like functions. I used the 7.2 SDK, but I do not think that the previous SDKs (like 7.0) were any different. Most likely older compilers/SDKs were just more forgiving. I believe it should still be buildable with 7.0.
> 
>     * As for `pluginConfigFile.append`, it was in the original patch, and actually I am not positive that it definitely fails. Do you think there is any room for an issue like not adding any slash at all? In my opinion, that was the point of appending the suffix manually.
> 
> 
> Kind regards,
> Vit

Thank you for replying, in fact your answer is really more informative then what i was going to say.

* for the `%a` yes you are completely correct, and `RetDecUint` is there to fix the problem specially for macOS, (clang is a really good compiler and warns about almost everything in compile time).

* `-DEA64=1` i tested with ON/OFF on macOS it seems not exporting the declaration (not accessible from sources) i don't know why, that's the reason i used it.

* i used SDK 7.0 to build both 32 and 64 bit plugins. don't have access to newer SDK. but should compile and see if it's not broken first.

* `retdec::utils::FilesystemPath` don't really remember i will test later and give you back.

**Comment by Maroc-OS** [comment]
I have to take a look into the source i did not touched it or used it from about a month or so :')

**Comment by PeterMatula** [comment]
@Maroc-OS can you please try to compile and check both 32-bit and 64-bit address space plugin variants from `pull-36` branch on macOS? I checked both on Linux and Windows and it looks ok. You don't have to run regression tests, since I don't know if they pass on macOS even for `master`. Just try to compile it and decompile some simple function in both `ida` and `ida64`.

I simplified and dumbed down CMake files but since I don't have macOS, I'm unable to check if it still works.

Build now generates and installs both 32-bit and 64-bit address space plugins at once, so there is no `EA64` option.
I also added regression tests for Mach-O decompilation, and decompilation via `idat64`, so if it works for you, I will consider this solved.

**Pull request merged**
